default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  host: db
  username: postgres
  password: secret

development:
  <<: *default
  database: appbooster_development

test:
  <<: *default
  database: appbooster_test

production:
  <<: *default
  database: appbooster_production
